package com.sparktech.InstaGet.controllers;

import com.sparktech.InstaGet.dtos.ProductDto;
import com.sparktech.InstaGet.services.AiService;
import com.sparktech.InstaGet.services.ProductService;
import com.sparktech.InstaGet.services.ResponseGenerator;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;

@Controller
public class AppController {

    @Autowired
    @Qualifier("geminiService")
    private AiService geminiService;

    @Autowired
    @Qualifier("chatGPTService")
    private AiService chatGPTService;

    @Autowired
    private ResponseGenerator responseGenerator;

    @Autowired
    private ProductService productService;

    @GetMapping("/HomePage")
    public String homePage() {
        return "HomePage";
    }

    @GetMapping("/products")
    public String productsPage(Model model) {
        model.addAttribute("products", productService.findAll());
        return "products";
    }

    @PostMapping("/products/add")
    public String addProduct(@RequestParam String name, @RequestParam double price, Model model) {
        productService.save(new ProductDto(0, name, price));
        model.addAttribute("products", productService.findAll());
        model.addAttribute("message", "Product added successfully!");
        return "products";
    }

    @PostMapping("/products/delete/{id}")
    public String deleteProduct(@PathVariable int id, Model model) {
        productService.delete(id);
        model.addAttribute("products", productService.findAll());
        model.addAttribute("message", "Product deleted successfully!");
        return "products";
    }

    @GetMapping("/ai")
    public String getAiResponse(@RequestParam(defaultValue = "gemini") String provider, Model model) {
        AiService aiService = provider.equalsIgnoreCase("chatgpt") ? chatGPTService : geminiService;
        responseGenerator.work(aiService);
        model.addAttribute("provider", provider);
        model.addAttribute("message", "Response generated by: " + provider);
        return "AiResponse";
    }
}
