package com.sparktech.InstaGet.controllers;

import com.sparktech.InstaGet.services.AiService;
import com.sparktech.InstaGet.services.ResponseGenerator;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;

@Controller
public class AppController {

    @Autowired
    @Qualifier("geminiService")
    private AiService geminiService;

    @Autowired
    @Qualifier("chatgptService")
    private AiService chatGPTService;

    @Autowired
    private ResponseGenerator responseGenerator;

    @GetMapping("/HomePage")
    public String homePage() {
        return "HomePage";
    }

    @GetMapping("/ai")
    public String getAiResponse(@RequestParam(defaultValue = "gemini") String provider, Model model) {
        AiService aiService = provider.equalsIgnoreCase("chatgpt") ? chatGPTService : geminiService;

        responseGenerator.work(aiService);

        model.addAttribute("provider", provider);
        model.addAttribute("message", "Response generated by: " + provider);
        return "AiResponse";
    }
}
